baseURL = 'https://223mle.github.io/'
languageCode = 'ja'
title = 'Daiki Tsutsumi'
theme = 'hugo-xmin'
[menu]

  [[menu.main]]
  name = "Home"
  url = ""
  weight = 1

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [Daiki Tsutsumi](https://223mle.github.io/) 2024 -- {Year} | [Github](https://github.com/223mle) | [Linkdin](https://www.linkedin.com/in/daiki-tsutsumi/)"

[markup]
  [markup.highlight]
  codeFences = false

